# Aula 6 Tera

# Decision Trees Study

> Este notebook tem o objetivo de guiar a aula 06 do bootcamp Tera dsc-fev2018.

> Trata-se de uma introdução a Machine Learning através de Decision Trees.

## Hello world!
>Esse é um caso facil e didatico. Vamos resolver o problema de ponta a ponta, porem de forma superficial. No proximo problema, nosso problema oficial, vamos entender como uma decision tree é criada.
![oranges_apples_ilustracao.png](../data/oranges_apples_ilustracao.png) [2]

### scikit-learn
![scikit-learn_fig](http://scikit-learn.org/stable/_static/scikit-learn-logo-small.png) [3]

[scikit-learn doc](http://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html)

In [127]:
#--Google Developers example
# from sklearn import tree
# features = [[140, 1], [130,1], [150,0], [170,0]]
# labels = [0, 0, 1, 1]
# clas_tree = tree.DecisionTreeClassifier()
# clas_tree = clas_tree.fit(features, labels)
# print(clas_tree.predict([[160,0]]))
# clas_tree.score(features,labels)

In [128]:
#--Import method decision tree from scikit-learn
from sklearn import tree

In [129]:
#--Define feautres weight, texture
features = [[140, 1], [130,1], [150,0], [170,0]]
labels = [0, 0, 1, 1]
print("features do elemento 0: {}".format(str((features[0]))))
print("label do elemento 0: {}".format(str((labels[0]))))

features do elemento 0: [140, 1]
label do elemento 0: 0


In [130]:
#--Instancia o classificador por Decision Tree
clas_tree = tree.DecisionTreeClassifier()
#--Treina o classificador com o dataset disponivel
clas_tree = clas_tree.fit(features, labels)

In [131]:
help(tree.DecisionTreeClassifier)

Help on class DecisionTreeClassifier in module sklearn.tree.tree:

class DecisionTreeClassifier(BaseDecisionTree, sklearn.base.ClassifierMixin)
 |  A decision tree classifier.
 |  
 |  Read more in the :ref:`User Guide <tree>`.
 |  
 |  Parameters
 |  ----------
 |  criterion : string, optional (default="gini")
 |      The function to measure the quality of a split. Supported criteria are
 |      "gini" for the Gini impurity and "entropy" for the information gain.
 |  
 |  splitter : string, optional (default="best")
 |      The strategy used to choose the split at each node. Supported
 |      strategies are "best" to choose the best split and "random" to choose
 |      the best random split.
 |  
 |  max_depth : int or None, optional (default=None)
 |      The maximum depth of the tree. If None, then nodes are expanded until
 |      all leaves are pure or until all leaves contain less than
 |      min_samples_split samples.
 |  
 |  min_samples_split : int, float, optional (default=2)

In [132]:
#--Estima uma fruta baseado em seu peso e textura, atraves do classificador Decision Tree
tests = [[120,1],
         [130,1],
         [100,1],
         [90,1],
         [200,1],
         [120,0],
         [130,0],
         [100,0],
         [90,0],
         [200,0]]
print(clas_tree.predict(tests)) #Observe que esse elemento nao existe no nosso dataset

[0 0 0 0 1 0 0 0 0 1]


---
## Iris case
>The Iris flower data set or Fisher's Iris data set is a multivariate data set introduced by the British statistician and biologist Ronald Fisher in his 1936 paper The use of multiple measurements in taxonomic problems as an example of linear discriminant analysis. [4]




| Elements | Taxonomy   |
|------|------|
|![Taxonomy hierarchy](../data/taxonomyHierarchy.png) [5]|![Iris elements](https://evolution.berkeley.edu/evolibrary/images/interviews/flower_diagram.gif "Iris elements") [1]|

Feature: Caracteristica do elemento de estudo.

Target: Variavel que se busca predizer.

In [133]:
#--Library
import os
import subprocess
from sklearn.tree import DecisionTreeClassifier, export_graphviz
import pandas as pd
import numpy as np
from sklearn import datasets

In [134]:
#--Load iris dataset
iris = datasets.load_iris()
print(iris.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [135]:
# Data from iris
print(dict(iris))

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [136]:
help(iris)

Help on Bunch in module sklearn.utils object:

class Bunch(builtins.dict)
 |  Container object for datasets
 |  
 |  Dictionary-like object that exposes its keys as attributes.
 |  
 |  >>> b = Bunch(a=1, b=2)
 |  >>> b['b']
 |  2
 |  >>> b.b
 |  2
 |  >>> b.a = 3
 |  >>> b['a']
 |  3
 |  >>> b.c = 6
 |  >>> b['c']
 |  6
 |  
 |  Method resolution order:
 |      Bunch
 |      builtins.dict
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __dir__(self)
 |      __dir__() -> list
 |      default dir() implementation
 |  
 |  __getattr__(self, key)
 |  
 |  __init__(self, **kwargs)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __setattr__(self, key, value)
 |      Implement setattr(self, name, value).
 |  
 |  __setstate__(self, state)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__


In [137]:
help(np.c_)

Help on CClass in module numpy.lib.index_tricks object:

class CClass(AxisConcatenator)
 |  Translates slice objects to concatenation along the second axis.
 |  
 |  This is short-hand for ``np.r_['-1,2,0', index expression]``, which is
 |  useful because of its common occurrence. In particular, arrays will be
 |  stacked along their last axis after being upgraded to at least 2-D with
 |  1's post-pended to the shape (column vectors made out of 1-D arrays).
 |  
 |  See Also
 |  --------
 |  column_stack : Stack 1-D arrays as columns into a 2-D array.
 |  r_ : For more detailed documentation.
 |  
 |  Examples
 |  --------
 |  >>> np.c_[np.array([1,2,3]), np.array([4,5,6])]
 |  array([[1, 4],
 |         [2, 5],
 |         [3, 6]])
 |  >>> np.c_[np.array([[1,2,3]]), 0, 0, np.array([[4,5,6]])]
 |  array([[1, 2, 3, 0, 0, 4, 5, 6]])
 |  
 |  Method resolution order:
 |      CClass
 |      AxisConcatenator
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self)
 |    

In [138]:
# Preparando o dataset para o dataframe
features = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']
df = pd.DataFrame(data=iris['data'],columns=features)

# O preditor funciona melhor quando o target é int
df['Target'] = iris['target'].astype(int)

# Test rows list
rows_test = [49,99,149]

# DataFrame de Treino
df_train = df.drop(df.index[rows_test])

# Dataframe de Test
df_test = df.iloc[rows_test]

# Visualizar parte do dataframe
df.iloc[40:60]

SepalLength  SepalWidth  PetalLength  PetalWidth  Target
40          5.0         3.5          1.3         0.3       0
41          4.5         2.3          1.3         0.3       0
42          4.4         3.2          1.3         0.2       0
43          5.0         3.5          1.6         0.6       0
44          5.1         3.8          1.9         0.4       0
45          4.8         3.0          1.4         0.3       0
46          5.1         3.8          1.6         0.2       0
47          4.6         3.2          1.4         0.2       0
48          5.3         3.7          1.5         0.2       0
49          5.0         3.3          1.4         0.2       0
50          7.0         3.2          4.7         1.4       1
51          6.4         3.2          4.5         1.5       1
52          6.9         3.1          4.9         1.5       1
53          5.5         2.3          4.0         1.3       1
54          6.5         2.8          4.6         1.5       1
55          5.7         2.8          4.5         1.3       1
56          6.3         3.3          4.7         1.6       1
57          4.9         2.4          3.3         1.0       1
58          6.6         2.9          4.6         1.3       1
59          5.2         2.7          3.9         1.4       1

In [139]:
#--Model data
Y = df_train['Target']
X = df_train[features]

dt = DecisionTreeClassifier(min_samples_split=20, random_state=99) #parameters to understand and modify
dt.fit(X, Y) #Train model

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=20,
            min_weight_fraction_leaf=0.0, presort=False, random_state=99,
            splitter='best')

In [140]:
#--Take a look at X (features) and y (target)
print("X:\n",X.head())
print("Y:\n",Y.head())

X:
    SepalLength  SepalWidth  PetalLength  PetalWidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2
Y:
 0    0
1    0
2    0
3    0
4    0
Name: Target, dtype: int64


In [141]:
#--Predict target
#dt.predict([[3,5,3,0]])
#dt.predict([[3,5,1,0]])
dt.predict(df_test[df_test['Target'] == 0][features])

array([0])

In [142]:
#--Check tree accuracy
dt.score(X,Y)

0.9795918367346939

### Gini
O Coeficiente de Gini é uma medida de desigualdade desenvolvida pelo estatístico italiano Corrado Gini, e publicada no documento "Variabilità e mutabilità" ("Variabilidade e mutabilidade" em italiano), em 1912.
https://pt.wikipedia.org/wiki/Coeficiente_de_Gini

## References
1. https://evolution.berkeley.edu/evolibrary/home.php 
2. https://www.youtube.com/watch?v=cKxRvEZd3Mw&list=PLOU2XLYxmsIIuiBfYad6rFYQU_jL2ryal
3. http://scikit-learn.org/stable/index.html#
4. https://en.wikipedia.org/wiki/Iris_flower_data_set
5. http://bioweb.uwlax.edu/bio203/s2012/zepke_pete/classification.htm
6. http://chrisstrelioff.ws/sandbox/2015/06/08/decision_trees_in_python_with_scikit_learn_and_pandas.html

---
## Supplementary material
### Original code from [6]

In [143]:
#--Library
# import os
# import subprocess
# from sklearn.tree import DecisionTreeClassifier, export_graphviz
# import pandas as pd
# import numpy as np
# from sklearn import datasets

# #--Abordagem alternativa, source: [6]
# ##Get Data

# #iris = datasets.load_iris() #option to read form scikit_learn datasets

# #Function to get the data local or remote
# def get_iris_data():
#     """Get the iris data, from local csv or pandas repo."""
#     if os.path.exists("iris.csv"):
#         print("-- iris.csv found locally")
#         df = pd.read_csv("iris.csv", index_col=0)
#     else:
#         print("-- trying to download from github")
#         fn = "https://raw.githubusercontent.com/pydata/pandas/" + \
#              "master/pandas/tests/data/iris.csv"
#         try:
#             df = pd.read_csv(fn)
#         except:
#             exit("-- Unable to download iris.csv")

#         with open("iris.csv", 'w') as f:
#             print("-- writing to local iris.csv file")
#             df.to_csv(f)

#     return df

# #Build the dataframe
# df = get_iris_data()

# df.head()

In [144]:
##Prepare data

# def encode_target(df, target_column):
#     """Add column to df with integers for the target.

#     Args
#     ----
#     df -- pandas DataFrame.
#     target_column -- column to map to int, producing
#                      new Target column.

#     Returns
#     -------
#     df_mod -- modified DataFrame.
#     targets -- list of target names.
#     """
#     df_mod = df.copy()
#     targets = df_mod[target_column].unique()
#     map_to_int = {name: n for n, name in enumerate(targets)}
#     df_mod["Target"] = df_mod[target_column].replace(map_to_int)

#     return (df_mod, targets)

# df2, targets = encode_target(df, "Name")
# df2[["Target", "Name"]].head()
# #Target variable is named as 'Target'

# #List features variables
# features = list(df2.columns[:4])
# #features
# df2.head()

In [145]:
##Model data

# y = df2["Target"]
# X = df2[features]
# dt = DecisionTreeClassifier(min_samples_split=20, random_state=99) #parameters to understand and modify
# dt.fit(X, y)

In [146]:
##Visualizing the tree

# def visualize_tree(tree, feature_names):
#     """Create tree png using graphviz.

#     Args
#     ----
#     tree -- scikit-learn DecsisionTree.
#     feature_names -- list of feature names.
#     """
#     with open("dt.dot", 'w') as f:
#         export_graphviz(tree, out_file=f,
#                         feature_names=feature_names)

#     command = ["dot", "-Tpng", "dt.dot", "-o", "dt.png"]
#     try:
#         subprocess.check_call(command)
#     except:
#         exit("Could not run dot, ie graphviz, to "
#              "produce visualization")
        
# visualize_tree(dt, features)


In [147]:
##Predict target

# dt.predict([[3,5,3,0]])

In [148]:
##Check tree accuracy

# dt.score(X,y)

---
### Functions to check version

In [ ]:
import sys
print(sys.version)